cabal-version:      3.0
name:               BacktestFunctor
version:            0.1.0.0
license:            MIT
license-file:       LICENSE
author:             Tuomas Myllymäki
maintainer:         myllymakituomas1998@gmail.com
category:           Math
build-type:         Simple
extra-doc-files:    CHANGELOG.md

common warnings
    ghc-options: -Wall -Wcompat -Wincomplete-record-updates
                 -Wincomplete-uni-patterns -Wredundant-constraints

common lang
    default-language:   GHC2021
    default-extensions: StrictData
                        DerivingStrategies
                        GeneralizedNewtypeDeriving

library
    import:           warnings, lang
    hs-source-dirs:   src
    exposed-modules:  Backtest.Execution,
                      Backtest.Market,
                      Backtest.Order,

    build-depends:    base ^>=4.20.2.0
                    , time
                    , containers
                    , cassava
                    , bytestring
                    , vector

executable BacktestFunctor
    import:           warnings, lang
    main-is:          Main.hs
    hs-source-dirs:   app
    build-depends:    base ^>=4.20.2.0
                    , BacktestFunctor

test-suite spec
    import:             warnings, lang
    type:               exitcode-stdio-1.0
    hs-source-dirs:     test
    main-is:            Spec.hs
    other-modules:      Backtest.FillSpec
    build-depends:      base ^>=4.20.2.0
                      , BacktestFunctor
                      , hspec
                      , QuickCheck
    build-tool-depends: hspec-discover:hspec-discover